# Generated by Django 5.2.7 on 2026-09-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('platform', models.CharField(choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok')], max_length=20)),
                ('format_type', models.CharField(choices=[('video', 'Video'), ('mp3', 'MP3')], default='video', max_length=10)),
                ('quality', models.CharField(default='1080p', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
